### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by Sispheor** [bovender/indicator-ip#12]
Here is a cute Kitten to thank you by advance for this feature.

![4fb6d17fdf8540005baf3d2a2ab5ac9e](https://user-images.githubusercontent.com/2573405/40120567-cc030672-591f-11e8-8d29-58449a620f96.jpg)

**Comment by bovender** [comment]
@Sispheor What are you trying to tell me? indicator-ip is available for Ubuntu 18.04 in my PPA, and me and others (#11) use it happily. Or do you use it, but there's a problem.

BTW I don't care about kittens at all.

**Comment by Sispheor** [comment]
Was not working after installing from the ppa.
As Ubuntu 18.04 is back on gnome I supposed that the support was not already present.
I'll dig into this then.

**Comment by Sispheor** [comment]
Ok, after a new reboot, the indicator apears by itself. So weird beause I did try to reboot after install the last time.
Anyway, it's ok for Ubuntu 18.04!
Thanks a lot for this useful tool.

**Comment by bovender** [comment]
Glad it works for you!
