### ISSUE TITLE
Support of Ubuntu 20.04

### ISSUE THREAD

**Issue by ae4ml** [bovender/indicator-ip#20]
This is currently not working with Ubuntu.20.04

$ sudo apt-get install indicator-ip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indicator-ip : Depends: python-appindicator but it is not installable
                Depends: python-gtk2 but it is not installable
E: Unable to correct problems, you have held broken packages.
$

**Comment by bovender** [comment]
This applet depends on Python 2, which is not longer included in Ubuntu 20.04 Focal Fossa. A replacement may be https://github.com/Sispheor/indicator-ip

Realizing that the PPA contains a package for Focal, I have just now requested deletion of that package. I'll also archive this repository.

Sorry about the inconvenience.
