### ISSUE TITLE
Add an auto refresh option

### ISSUE THREAD

**Issue by adamdry** [bovender/indicator-ip#5]
Would it be possible to add an option whereby the ip address is auto refreshed every x seconds (60 seconds for example)? Thanks!

**Comment by bovender** [comment]
The IP is refreshed automatically whenever the network connection status changes. Does it not do that on your system? It has been working perfectly over here for almost 2 years now.

**Comment by adamdry** [comment]
Apologies, this works fine! Thanks for creating it btw, it's very helpful for me!

**Comment by cjohnston1158** [comment]
I've setup my router to use an external VPN, so my hope was that if the VPN got disconnected, causing my external IP to change, that this indicator would be able to notify me visually. I don't believe this would cause any status changes on the local machine though, triggering the .refresh()

**Comment by bovender** [comment]
Ah, ok, got it. It does work well with VPNs created from within the operating system (that's my everyday use case).

I'm really not a Python programmer, and this was only a side project. So let's see if I can figure out how to set up a timer in Python...
