### ISSUE TITLE
show CIDR netmask

### ISSUE THREAD

**Issue by Sispheor** [bovender/indicator-ip#6]
Could be very useful to know the subnet like `192.168.0.12/24`.

**Comment by bovender** [comment]
This would only be applicable for local interfaces, right? In theory, a remote IP can also be on a subnet, but I wouldn't know how to get this information.

**Comment by Sispheor** [comment]
Yes yes of course, only for the private lan. I just say that because I work in a company with a lot of different subnet. I type `ip a` all day long. You module save me a lot of time :) Thank you for that.
